// Store PostgreSQL database models here
/* 
    First item in each table list is the name of the Postgres table and should match the collection name in MongoDB
    Second item in each table should be the Primary Key item
    Third item onwards are the columns that you want to migrate from MongoDB to Postgres. The names should match the MongoDB names, unless you want to create a custom rule in the migration script 
*/

module.exports.all_models = {
  // mongo_dummy_data_books_model: [
  //   "mongo_dummy_data_books", // first item is always table / collection name
  //   "_id VARCHAR(50) PRIMARY KEY NOT NULL", // second item is primary key field
  //   "title TEXT",
  //   "isbn VARCHAR(100)",
  //   "pageCount INT4",
  //   "created_at TIMESTAMPTZ",
  //   "thumbnailUrl VARCHAR(200)",
  //   "shortDescription TEXT",
  //   "longDescription TEXT",
  //   "status VARCHAR(50)",
  //   "authors _TEXT", // array - _ before field type
  //   "categories _TEXT",
  // ],
  // mongo_dummy_data_countries_model: [
  //   "mongo_dummy_data_countries",
  //   "_id VARCHAR(50) PRIMARY KEY NOT NULL",
  //   "altSpellings _TEXT",
  //   "area NUMERIC",
  //   "borders _TEXT",
  //   "callingCode _TEXT",
  //   "capital VARCHAR(100)",
  //   "languages JSONB", // JSONB
  //   "common_name VARCHAR(100)", // Custom field - see  migrate_data.js for details
  // ],
  // mongo_dummy_data_profiles_model: [
  //   "mongo_dummy_data_profiles",
  //   "_id VARCHAR(50) PRIMARY KEY NOT NULL",
  //   "client TEXT",
  //   "updated_at TIMESTAMPTZ", //updated_at and created_at fields can be used to auto update data dynamically
  // ],

  unit: [
    "units",
    "_id VARCHAR(50) PRIMARY KEY NOT NULL",
    "name TEXT",
    "uid TEXT",
    "code  TEXT",
    "parent  VARCHAR(50)",
    "type TEXT",
    "state TEXT",
    "subcounty TEXT",
    "county TEXT",
    "suggestions _TEXT",
    "updatedAt TIMESTAMP",
    "createdAt TIMESTAMP",
  ],

  // app: [
  //   "apps",
  //   "_id VARCHAR(50) PRIMARY KEY NOT NULL",
  //   "userId VARCHAR(50)",
  //   "name TEXT",
  //   "id TEXT",
  //   "packageName  TEXT",
  //   "version  TEXT",
  //   "buildNumber  TEXT",
  //   "token  TEXT",
  //   "updatedAt TIMESTAMP",
  //   "createdAt TIMESTAMP",
  // ],

  user: [
    "users",
    "_id VARCHAR(50) PRIMARY KEY NOT NULL",
    "displayName TEXT",
    "phoneNumber TEXT",
    "status TEXT",
    "suggestions _TEXT",
    "updatedAt TIMESTAMP",
    "createdAt TIMESTAMP",
  ],

  role: [
    "roles",
    "_id VARCHAR(50) PRIMARY KEY NOT NULL",
    "userId VARCHAR(50)",
    "unit VARCHAR(50)",
    "status TEXT",
    "spot TEXT",
    "updatedAt TIMESTAMP",
    "createdAt TIMESTAMP",

  ],

  // tag: [
  //   "tags",
  //   "_id VARCHAR(50) PRIMARY KEY NOT NULL",
  //   "text TEXT",
  //   "posts INT",
  //   "updatedAt TIMESTAMP",
  //   "createdAt TIMESTAMP",
  // ],

  // incomingSMS: [
  //   "incomingsms",
  //   "_id VARCHAR(50) PRIMARY KEY NOT NULL",
  //   "id TEXT",
  //   "date TIMESTAMP",
  //   "text TEXT",
  //   "cost TEXT",
  //   "networkCode TEXT",
  //   "updatedAt TIMESTAMP",
  //   "createdAt TIMESTAMP",
  //   "_to TEXT",
  //   "_from TEXT",
  // ],

  task: [
    "tasks",
    "_id VARCHAR(50) PRIMARY KEY NOT NULL",
    "userId VARCHAR(50)",
    "signalId VARCHAR(50)",
    "signal TEXT",
    "units _TEXT",
    "unitId VARCHAR(50)",
    "status TEXT",
    "state TEXT",
    "name TEXT",
    "type TEXT",
    "subcounty TEXT",
    "county TEXT",
    "via TEXT",
    "updatedAt TIMESTAMP",
    "createdAt TIMESTAMP",

    //PMEBS Report Form
    "pmebs_reportForm_id VARCHAR(50)",
    "pmebs_reportForm_user VARCHAR(50)",
    "pmebs_reportForm_dateDetected TIMESTAMP",
    "pmebs_reportForm_dateReported TIMESTAMP",
    "pmebs_reportForm_description TEXT",
    "pmebs_reportForm_source TEXT",
    "pmebs_reportForm_unit VARCHAR(50)",
    "pmebs_reportForm_locality TEXT",
    "pmebs_reportForm_createdAt TIMESTAMP",
    "pmebs_reportForm_updatedAt TIMESTAMP",

    //PMEBS Request Form
    "pmebs_requestForm_id VARCHAR(50)",
    "pmebs_requestForm_user VARCHAR(50)",
    "pmebs_requestForm_dateReported TIMESTAMP",
    "pmebs_requestForm_dateRequested TIMESTAMP",
    "pmebs_requestForm_description TEXT",
    "pmebs_requestForm_unit VARCHAR(50)",
    "pmebs_requestForm_locality TEXT",
    "pmebs_requestForm_createdAt TIMESTAMP",
    "pmebs_requestForm_updatedAt TIMESTAMP",

    "pmebs_id VARCHAR(50)",
    "pmebs_createdAt TIMESTAMP",
    "pmebs_updatedAt TIMESTAMP",

    //VEBS Verification Form
    "vebs_verificationForm_id VARCHAR(50)",
    "vebs_verificationForm_user VARCHAR(50)",
    "vebs_verificationForm_description TEXT",
    "vebs_verificationForm_source TEXT",
    "vebs_verificationForm_isMatchingSignal TEXT",
    "vebs_verificationForm_updatedSignal TEXT",
    "vebs_verificationForm_isReportedBefore TEXT",
    "vebs_verificationForm_dateHealthThreatStarted TIMESTAMP",
    "vebs_verificationForm_dateVerified TIMESTAMP",
    "vebs_verificationForm_dateSCDSCInformed TIMESTAMP",
    "vebs_verificationForm_informant TEXT",
    "vebs_verificationForm_otherInformant TEXT",
    "vebs_verificationForm_additionalInformation TEXT",
    "vebs_verificationForm_isThreatStillExisting TEXT",
    "vebs_verificationForm_threatTo TEXT",
    "vebs_verificationForm_via TEXT",
    "vebs_verificationForm_createdAt TIMESTAMP",
    "vebs_verificationForm_updatedAt TIMESTAMP",

    //VEBS Investigation Form
    "vebs_investigationForm_id VARCHAR(50)",
    "vebs_investigationForm_user VARCHAR(50)",
    "vebs_investigationForm_symptoms TEXT",
    "vebs_investigationForm_humansCases INTEGER",
    "vebs_investigationForm_humansCasesHospitalized INTEGER",
    "vebs_investigationForm_humansDead INTEGER",
    "vebs_investigationForm_animalsCases INTEGER",
    "vebs_investigationForm_animalsDead INTEGER",
    "vebs_investigationForm_isCauseKnown TEXT",
    "vebs_investigationForm_cause TEXT",
    "vebs_investigationForm_isLabSamplesCollected TEXT",
    "vebs_investigationForm_labResults TEXT",
    "vebs_investigationForm_dateEventStarted TIMESTAMP",
    "vebs_investigationForm_dateInvestigationStarted TIMESTAMP",
    "vebs_investigationForm_dateSCDSCInformed TIMESTAMP",
    "vebs_investigationForm_dateSCMOHInformed TIMESTAMP",
    "vebs_investigationForm_dateLabResultsReceived TIMESTAMP",
    "vebs_investigationForm_dateSampleCollected TIMESTAMP",
    "vebs_investigationForm_isNewCasedReportedFromInitialArea TEXT",
    "vebs_investigationForm_isNewCasedReportedFromNewAreas TEXT",
    "vebs_investigationForm_isEventSettingPromotingSpread TEXT",
    "vebs_investigationForm_additionalInformation TEXT",
    "vebs_investigationForm_riskClassification TEXT",
    "vebs_investigationForm_via TEXT",
    "vebs_investigationForm_responseActivities _TEXT",
    "vebs_investigationForm_createdAt TIMESTAMP",
    "vebs_investigationForm_updatedAt TIMESTAMP",

    //VEBS Response Form
    "vebs_responseForm_id VARCHAR(50)",
    "vebs_responseForm_user VARCHAR(50)",
    "vebs_responseForm_dateSCMOHInformed TIMESTAMP",
    "vebs_responseForm_dateResponseStarted TIMESTAMP",
    "vebs_responseForm_dateEscalated TIMESTAMP",
    "vebs_responseForm_dateOfReport TIMESTAMP",
    "vebs_responseForm_responseActivities _TEXT",
    "vebs_responseForm_otherResponseActivity TEXT",
    "vebs_responseForm_outcomeOfResponse TEXT",
    "vebs_responseForm_recommendations _TEXT",
    "vebs_responseForm_additionalInformation TEXT",
    "vebs_responseForm_via TEXT",
    "vebs_responseForm_createdAt TIMESTAMP",
    "vebs_responseForm_updatedAt TIMESTAMP",

    //VEBS Escalation Form
    "vebs_escalationForm_id VARCHAR(50)",
    "vebs_escalationForm_user VARCHAR(50)",
    "vebs_escalationForm_dateResponseStarted TIMESTAMP",
    "vebs_escalationForm_dateEscalated TIMESTAMP",
    "vebs_escalationForm_reason TEXT",
    "vebs_escalationForm_reasonOther TEXT",
    "vebs_escalationForm_via TEXT",
    "vebs_escalationForm_createdAt TIMESTAMP",
    "vebs_escalationForm_updatedAt TIMESTAMP",
    "vebs_id VARCHAR(50)",
    "vebs_createdAt TIMESTAMP",
    "vebs_updatedAt TIMESTAMP",

    //CEBS Verification Form
    "cebs_verificationForm_id VARCHAR(50)",
    "cebs_verificationForm_user VARCHAR(50)",
    "cebs_verificationForm_description TEXT",
    "cebs_verificationForm_source TEXT",
    "cebs_verificationForm_isMatchingSignal TEXT",
    "cebs_verificationForm_updatedSignal TEXT",
    "cebs_verificationForm_isReportedBefore TEXT",
    "cebs_verificationForm_dateHealthThreatStarted TIMESTAMP",
    "cebs_verificationForm_dateVerified TIMESTAMP",
    "cebs_verificationForm_dateSCDSCInformed TIMESTAMP",
    "cebs_verificationForm_informant TEXT",
    "cebs_verificationForm_otherInformant TEXT",
    "cebs_verificationForm_additionalInformation TEXT",
    "cebs_verificationForm_isThreatStillExisting TEXT",
    "cebs_verificationForm_threatTo TEXT",
    "cebs_verificationForm_via TEXT",
    "cebs_verificationForm_createdAt TIMESTAMP",
    "cebs_verificationForm_updatedAt TIMESTAMP",

    //CEBS Investigation Form
    "cebs_investigationForm_id VARCHAR(50)",
    "cebs_investigationForm_user VARCHAR(50)",
    "cebs_investigationForm_symptoms TEXT",
    "cebs_investigationForm_humansCases INTEGER",
    "cebs_investigationForm_humansCasesHospitalized INTEGER",
    "cebs_investigationForm_humansDead INTEGER",
    "cebs_investigationForm_animalsCases INTEGER",
    "cebs_investigationForm_animalsDead INTEGER",
    "cebs_investigationForm_isCauseKnown TEXT",
    "cebs_investigationForm_cause TEXT",
    "cebs_investigationForm_isLabSamplesCollected TEXT",
    "cebs_investigationForm_labResults TEXT",
    "cebs_investigationForm_dateEventStarted TIMESTAMP",
    "cebs_investigationForm_dateInvestigationStarted TIMESTAMP",
    "cebs_investigationForm_dateSCDSCInformed TIMESTAMP",
    "cebs_investigationForm_dateSCMOHInformed TIMESTAMP",
    "cebs_investigationForm_dateLabResultsReceived TIMESTAMP",
    "cebs_investigationForm_dateSampleCollected TIMESTAMP",
    "cebs_investigationForm_isNewCasedReportedFromInitialArea TEXT",
    "cebs_investigationForm_isNewCasedReportedFromNewAreas TEXT",
    "cebs_investigationForm_isEventSettingPromotingSpread TEXT",
    "cebs_investigationForm_additionalInformation TEXT",
    "cebs_investigationForm_riskClassification TEXT",
    "cebs_investigationForm_via TEXT",
    "cebs_investigationForm_responseActivities _TEXT",
    "cebs_investigationForm_createdAt TIMESTAMP",
    "cebs_investigationForm_updatedAt TIMESTAMP",

    //CEBS Response Form
    "cebs_responseForm_id VARCHAR(50)",
    "cebs_responseForm_user VARCHAR(50)",
    "cebs_responseForm_dateSCMOHInformed TIMESTAMP",
    "cebs_responseForm_dateResponseStarted TIMESTAMP",
    "cebs_responseForm_dateEscalated TIMESTAMP",
    "cebs_responseForm_dateOfReport TIMESTAMP",
    "cebs_responseForm_responseActivities _TEXT",
    "cebs_responseForm_otherResponseActivity TEXT",
    "cebs_responseForm_outcomeOfResponse TEXT",
    "cebs_responseForm_recommendations _TEXT",
    "cebs_responseForm_additionalInformation TEXT",
    "cebs_responseForm_via TEXT",
    "cebs_responseForm_createdAt TIMESTAMP",
    "cebs_responseForm_updatedAt TIMESTAMP",

    //CEBS Escalation Form
    "cebs_escalationForm_id VARCHAR(50)",
    "cebs_escalationForm_user VARCHAR(50)",
    "cebs_escalationForm_dateResponseStarted TIMESTAMP",
    "cebs_escalationForm_dateEscalated TIMESTAMP",
    "cebs_escalationForm_reason TEXT",
    "cebs_escalationForm_reasonOther TEXT",
    "cebs_escalationForm_via TEXT",
    "cebs_escalationForm_createdAt TIMESTAMP",
    "cebs_escalationForm_updatedAt TIMESTAMP",
    "cebs_id VARCHAR(50)",
    "cebs_createdAt TIMESTAMP",
    "cebs_updatedAt TIMESTAMP",

    //HEBS Verification Form
    "hebs_verificationForm_id VARCHAR(50)",
    "hebs_verificationForm_user VARCHAR(50)",
    "hebs_verificationForm_description TEXT",
    "hebs_verificationForm_source TEXT",
    "hebs_verificationForm_isMatchingSignal TEXT",
    "hebs_verificationForm_updatedSignal TEXT",
    "hebs_verificationForm_isReportedBefore TEXT",
    "hebs_verificationForm_dateHealthThreatStarted TIMESTAMP",
    "hebs_verificationForm_dateVerified TIMESTAMP",
    "hebs_verificationForm_dateSCDSCInformed TIMESTAMP",
    "hebs_verificationForm_informant TEXT",
    "hebs_verificationForm_otherInformant TEXT",
    "hebs_verificationForm_additionalInformation TEXT",
    "hebs_verificationForm_isThreatStillExisting TEXT",
    "hebs_verificationForm_threatTo TEXT",
    "hebs_verificationForm_via TEXT",
    "hebs_verificationForm_createdAt TIMESTAMP",
    "hebs_verificationForm_updatedAt TIMESTAMP",

    //HEBS Investigation Form
    "hebs_investigationForm_id VARCHAR(50)",
    "hebs_investigationForm_user VARCHAR(50)",
    "hebs_investigationForm_symptoms TEXT",
    "hebs_investigationForm_humansCases INTEGER",
    "hebs_investigationForm_humansCasesHospitalized INTEGER",
    "hebs_investigationForm_humansDead INTEGER",
    "hebs_investigationForm_animalsCases INTEGER",
    "hebs_investigationForm_animalsDead INTEGER",
    "hebs_investigationForm_isCauseKnown TEXT",
    "hebs_investigationForm_cause TEXT",
    "hebs_investigationForm_isLabSamplesCollected TEXT",
    "hebs_investigationForm_labResults TEXT",
    "hebs_investigationForm_dateEventStarted TIMESTAMP",
    "hebs_investigationForm_dateInvestigationStarted TIMESTAMP",
    "hebs_investigationForm_dateSCDSCInformed TIMESTAMP",
    "hebs_investigationForm_dateSCMOHInformed TIMESTAMP",
    "hebs_investigationForm_dateLabResultsReceived TIMESTAMP",
    "hebs_investigationForm_dateSampleCollected TIMESTAMP",
    "hebs_investigationForm_isNewCasedReportedFromInitialArea TEXT",
    "hebs_investigationForm_isNewCasedReportedFromNewAreas TEXT",
    "hebs_investigationForm_isEventSettingPromotingSpread TEXT",
    "hebs_investigationForm_additionalInformation TEXT",
    "hebs_investigationForm_riskClassification TEXT",
    "hebs_investigationForm_via TEXT",
    "hebs_investigationForm_responseActivities _TEXT",
    "hebs_investigationForm_createdAt TIMESTAMP",
    "hebs_investigationForm_updatedAt TIMESTAMP",

    //HEBS Response Form
    "hebs_responseForm_id VARCHAR(50)",
    "hebs_responseForm_user VARCHAR(50)",
    "hebs_responseForm_dateSCMOHInformed TIMESTAMP",
    "hebs_responseForm_dateResponseStarted TIMESTAMP",
    "hebs_responseForm_dateEscalated TIMESTAMP",
    "hebs_responseForm_dateOfReport TIMESTAMP",
    "hebs_responseForm_responseActivities _TEXT",
    "hebs_responseForm_otherResponseActivity TEXT",
    "hebs_responseForm_outcomeOfResponse TEXT",
    "hebs_responseForm_recommendations _TEXT",
    "hebs_responseForm_additionalInformation TEXT",
    "hebs_responseForm_via TEXT",
    "hebs_responseForm_createdAt TIMESTAMP",
    "hebs_responseForm_updatedAt TIMESTAMP",

    //HEBS Escalation Form
    "hebs_escalationForm_id VARCHAR(50)",
    "hebs_escalationForm_user VARCHAR(50)",
    "hebs_escalationForm_dateResponseStarted TIMESTAMP",
    "hebs_escalationForm_dateEscalated TIMESTAMP",
    "hebs_escalationForm_reason TEXT",
    "hebs_escalationForm_reasonOther TEXT",
    "hebs_escalationForm_via TEXT",
    "hebs_escalationForm_createdAt TIMESTAMP",
    "hebs_escalationForm_updatedAt TIMESTAMP",
    "hebs_id VARCHAR(50)",
    "hebs_createdAt TIMESTAMP",
    "hebs_updatedAt TIMESTAMP",

    //lEBS Verification Form
    "lebs_verificationForm_id VARCHAR(50)",
    "lebs_verificationForm_user VARCHAR(50)",
    "lebs_verificationForm_description TEXT",
    "lebs_verificationForm_isMatchingSignal TEXT",
    "lebs_verificationForm_updatedSignal TEXT",
    "lebs_verificationForm_isReportedBefore TEXT",
    "lebs_verificationForm_dateHealthThreatStarted TIMESTAMP",
    "lebs_verificationForm_dateVerified TIMESTAMP",
    "lebs_verificationForm_dateSCDSCInformed TIMESTAMP",
    "lebs_verificationForm_informant TEXT",
    "lebs_verificationForm_otherInformant TEXT",
    "lebs_verificationForm_additionalInformation TEXT",
    "lebs_verificationForm_isStillHappening TEXT",
    "lebs_verificationForm_via TEXT",
    "lebs_verificationForm_createdAt TIMESTAMP",
    "lebs_verificationForm_updatedAt TIMESTAMP",

    //lEBS Investigation Form
    "lebs_investigationForm_id VARCHAR(50)",
    "lebs_investigationForm_user VARCHAR(50)",
    "lebs_investigationForm_symptoms TEXT",
    "lebs_investigationForm_symptomsOther TEXT",
    "lebs_investigationForm_isSamplesCollected TEXT",
    "lebs_investigationForm_labResults TEXT",
    "lebs_investigationForm_dateEventStarted TIMESTAMP",
    "lebs_investigationForm_dateInvestigationStarted TIMESTAMP",
    "lebs_investigationForm_dateSCDSCInformed TIMESTAMP",
    "lebs_investigationForm_dateRRTInformed TIMESTAMP",
    "lebs_investigationForm_dateLabResultsReceived TIMESTAMP",
    "lebs_investigationForm_dateSampleCollected TIMESTAMP",
    "lebs_investigationForm_isCovid19WorkingCaseDefinitionMet TEXT",
    "lebs_investigationForm_isEventSettingPromotingSpread TEXT",
    "lebs_investigationForm_measureHandHygiene TEXT",
    "lebs_investigationForm_measureTempScreening TEXT",
    "lebs_investigationForm_measurePhysicalDistancing TEXT",
    "lebs_investigationForm_measureUseOfMasks TEXT",
    "lebs_investigationForm_measureVentilation TEXT",
    "lebs_investigationForm_measureSocialDistancing TEXT",
    "lebs_investigationForm_additionalInformation TEXT",
    "lebs_investigationForm_riskClassification TEXT",
    "lebs_investigationForm_via TEXT",
    "lebs_investigationForm_responseActivities _TEXT",
    "lebs_investigationForm_createdAt TIMESTAMP",
    "lebs_investigationForm_updatedAt TIMESTAMP",

    //lEBS Response Form
    "lebs_responseForm_id VARCHAR(50)",
    "lebs_responseForm_user VARCHAR(50)",
    "lebs_responseForm_dateSCMOHInformed TIMESTAMP",
    "lebs_responseForm_dateResponseStarted TIMESTAMP",
    "lebs_responseForm_dateSamplesCollected TIMESTAMP",
    "lebs_responseForm_dateOfTestResults TIMESTAMP",
    "lebs_responseForm_isCovid19WorkingCaseDefinitionMet TEXT",
    "lebs_responseForm_isCIFFilledAndSamplesCollected TEXT",
    "lebs_responseForm_reasonsNoSampleCollectedOther TEXT",
    "lebs_responseForm_responseActivitiesOther TEXT",
    "lebs_responseForm_isHumansQuarantinedFollowedUp TEXT",
    "lebs_responseForm_eventStatus TEXT",
    "lebs_responseForm_humansQuarantinedSelf INTEGER",
    "lebs_responseForm_humansQuarantinedSchool INTEGER",
    "lebs_responseForm_humansQuarantinedInstitutional INTEGER",
    "lebs_responseForm_humansIsolationSchool INTEGER",
    "lebs_responseForm_humansIsolationHealthFacility INTEGER",
    "lebs_responseForm_humansIsolationHome INTEGER",
    "lebs_responseForm_humansIsolationInstitutional INTEGER",
    "lebs_responseForm_humansDead INTEGER",
    "lebs_responseForm_humansPositive INTEGER",
    "lebs_responseForm_humansTested INTEGER",
    "lebs_responseForm_humansCases INTEGER",
    "lebs_responseForm_humansQuarantined INTEGER",
    "lebs_responseForm_quarantineTypes _TEXT",
    "lebs_responseForm_isHumansIsolated _TEXT",
    "lebs_responseForm_isolationTypes _TEXT",
    "lebs_responseForm_eventStatuses _TEXT",
    "lebs_responseForm_responseActivities _TEXT",
    "lebs_responseForm_additionalResponseActivities _TEXT",
    "lebs_responseForm_reasonsNoSampleCollected _TEXT",
    "lebs_responseForm_additionalInformation TEXT",
    "lebs_responseForm_via TEXT",
    "lebs_responseForm_createdAt TIMESTAMP",
    "lebs_responseForm_updatedAt TIMESTAMP",

    //lEBS Escalation Form
    "lebs_escalationForm_id VARCHAR(50)",
    "lebs_escalationForm_user VARCHAR(50)",
    "lebs_escalationForm_dateResponseStarted TIMESTAMP",
    "lebs_escalationForm_dateEscalated TIMESTAMP",
    "lebs_escalationForm_reason TEXT",
    "lebs_escalationForm_reasonOther TEXT",
    "lebs_escalationForm_via TEXT",
    "lebs_escalationForm_createdAt TIMESTAMP",
    "lebs_escalationForm_updatedAt TIMESTAMP",
    "lebs_id VARCHAR(50)",
    "lebs_createdAt TIMESTAMP",
    "lebs_updatedAt TIMESTAMP",
  ],
};
